version: '3.4'

services:
  tiendaservicios.api.autor:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapiautor
    build:
      context: .
      dockerfile: TiendaServicios.Api.Autor/Dockerfile

  tiendaservicios.api.libros:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapilibros
    build:
      context: .
      dockerfile: TiendaServicios.Api.Libros/Dockerfile

  tiendaservicios.api.carritocompra:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapicarritocompra
    build:
      context: .
      dockerfile: TiendaServicios.Api.CarritoCompra/Dockerfile

  tiendaservicios.api.gateway:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapigateway
    build:
      context: .
      dockerfile: TiendaServicios.Api.Gateway/Dockerfile

networks:
    default:
        external:
            name: microservicenet



